### ISSUE TITLE
Model is not saving in models folder

### ISSUE THREAD

**Issue by atharvaathaley** [Hguimaraes/gtzan.keras#13]
Hello,
My training is successfully executed and after that when i go for testing i dont see any additional files in my model folder. Can you please help me urgently because this is my Final year project.
Thanks in advance

**Comment by Hguimaraes** [comment]
Hi @atharvaathaley 

I just update a new version of the project in commit e3f5eba.
I updated the packages, the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

Cheers,

**Comment by atharvaathaley** [comment]
ok @Hguimaraes sir! Will do that!
