### ISSUE TITLE
    model = Model(inputs=vgg16.input, outputs=top(vgg16.output)) NameError: name 'Model' is not defined

### ISSUE THREAD

**Issue by PremVarma** [Hguimaraes/gtzan.keras#14]

**Comment by atharvaathaley** [comment]
@PremVarma in src/gtzan folder. There is a model.py file. Open it, add "From keras import Model" and save it

**Comment by PremVarma** [comment]
Thanks a lot ..(: what about evaluate_test ? 
its missing..

**Comment by atharvaathaley** [comment]
facing same problem. No idea about that

**Comment by Hguimaraes** [comment]
Hey guys,

As discussed in another thread, the evaluate_test implementation was missing.
I just update a new version of the project in commit e3f5eba.
I updated the packages, the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

Cheers,
