### ISSUE TITLE
Why can't I reproduce the experimental results?

### ISSUE THREAD

**Issue by sjtu-cz** [Hguimaraes/gtzan.keras#15]
I download the dataset, And after 12 epoches , the acc is still 0.1, Was anyone reproduced the results? 
![image](https://user-images.githubusercontent.com/20858982/67673535-4398e080-f9b5-11e9-8cb5-88de692f4a34.png)

**Comment by Hguimaraes** [comment]
Hi @sjtu-cz,

I just update a new version of the project in commit e3f5eba662f16f684105fc177fc05090035ae442. 
I updated the packages, the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

Cheers,
