### ISSUE TITLE
Error gtzan.data

### ISSUE THREAD

**Issue by atharvaathaley** [Hguimaraes/gtzan.keras#16]
Hello and sorry to disturb you again but I am getting an error again which is shown in the photo. Please help me as this is my final year project. 
Thank you.
![Capture](https://user-images.githubusercontent.com/52083371/72749970-8bf52280-3be1-11ea-925d-f0ea12d576cc.PNG)

**Comment by Hguimaraes** [comment]
@atharvaathaley 

I fixed in the last commit. The file was being ignored by gitingore, sorry for that.

Cheers,
