### ISSUE TITLE
I am getting this error. please help

### ISSUE THREAD

**Issue by atharvaathaley** [Hguimaraes/gtzan.keras#18]
![Capture](https://user-images.githubusercontent.com/52083371/75653750-31d98980-5c84-11ea-95f1-b386f7f9c946.PNG)

**Comment by Hguimaraes** [comment]
Hi @atharvaathaley,

I need to look more in detail, but it looks like is from Librosa on Windows. Could you try to run a Librosa example and see if works? Also try to install ffmpeg on your Windows setup.

I have developed the project using a Ubuntu 18.04 version and Python 3.7.4. Please use the packages specified on the requirements.txt

Cheers,
