### ISSUE TITLE
Where is the number 300 comming from?

### ISSUE THREAD

**Issue by galloj** [Hguimaraes/gtzan.keras#25]
In file https://github.com/Hguimaraes/gtzan.keras/blob/master/nbs/1.1-custom_cnn_2d.ipynb theres number 300 used in majority voting, can you please explain where does this number comes from? It would be really nice to know, because after changing amount of genres and songs this part of script stops working.

**Comment by willnufe** [comment]
My English is not very good. First, you should know the y_test.shape is (11700, 10). After the operation of `np.argmax(y_test, axis=1)`, the shape of y_test is turned into (11700,). Each sound was divided into 39 segments in our custom function, the test dataset has 300 songs. so 11700 = 39 * 300.
