### ISSUE TITLE
Where is evaluate_test?

### ISSUE THREAD

**Issue by SreeHarshaNelaturu** [Hguimaraes/gtzan.keras#4]
In gtzan.py, for using it as test "evaluate_test" is missing, am I missing something out, or has it not been provided?

**Comment by Hguimaraes** [comment]
Hi @SreeHarshaNelaturu

You are right, I'm sorry for that. Since I tested everything on a Jupyter notebook, I put this on my to-do list and I totally forgot. I will implement as soon as I can (Probably not before 14/12 :-/ )

Cheers,

**Comment by SreeHarshaNelaturu** [comment]
That's awesome thanks, made a pull request with a rough evaluation using your code. I seem to be getting very bad predictions, am I doing the evaluation wrong, if you could let me know that would be great.

**Comment by JMAPeters** [comment]
Is there a better solution then the soluction of SreeHarshaNelat ?

**Comment by Hguimaraes** [comment]
Hey guys,

I just update a new version of the project in commit e3f5eba.
I updated the packages, the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

The solution of @SreeHarshaNelaturu is perfect for that version and I appreciate the effort he did to improve the project!

Cheers,
