### ISSUE TITLE
can you please provide cnn model which is saved in models folder because it is taking too much time to train the model

### ISSUE THREAD

**Issue by tusharaherkar** [Hguimaraes/gtzan.keras#6]

**Comment by NazarPonochevnyi** [comment]
Hello!
I posted weights here: https://github.com/NazarPonochevnyi/Trained-CNN-for-Genre-classification

**Comment by Hguimaraes** [comment]
Hey guys, I'm closing this issue. The project will pass through a (big) refactoring, corrections and updates. Also, I will make available the new weights.

Cheers
