### ISSUE TITLE
missing evaluate_test  ?

### ISSUE THREAD

**Issue by creazyyuan** [Hguimaraes/gtzan.keras#9]
hello,when I run gtzan.py,I found evaluate_test method has missing in your code,I view issues,found some guy has raised this question.Until now,you had not add this method, Can you add this method as soon as you can ? thanks you very much

**Comment by HachimiLearning** [comment]
Me too I really want this method maybe can we contact the author by email @creazyyuan

**Comment by Hguimaraes** [comment]
Hey guys,

Just to let you know, I'm reading all the issues and planning on how to work-on. 
The only problem is that right now I don't have a PC capable of running this project, so I will take some time to fix this, but I will. I'm sorry for all the problems.

Cheers,

**Comment by Hguimaraes** [comment]
Hi @creazyyuan and @HachimiMar 

I just update a new version of the project in commit e3f5eba.
I updated the packages, the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

Cheers,
